#!/usr/bin/env bash
#
#  Copyright (c) 2022, Mikhail Krichanov. All rights reserved.
#  SPDX-License-Identifier: BSD-3-Clause
#
full_cmd=${BASH_SOURCE:-$0} # see http://mywiki.wooledge.org/BashFAQ/028 for a discussion of why $0 is not a good choice here
dir=$(dirname "$full_cmd")
cmd=${full_cmd##*/}

if [ -n "$WORKSPACE" ] && [ -e "$EDK_TOOLS_PATH/ImageTool" ]
then
  if [ ! -e "$EDK_TOOLS_PATH/ImageTool/ImageTool" ]
  then
    echo "BaseTools C Tool binary was not found (ImageTool)"
    echo "You may need to run:"
    echo "  make -C $EDK_TOOLS_PATH/ImageTool"
  else
    exec "$EDK_TOOLS_PATH/ImageTool/ImageTool" "$@"
  fi
else
  echo "Unable to find the real '$cmd' to run"
  echo "This message was printed by"
  echo "  $0"
  exit 127
fi
