#!/usr/bin/env bash

full_cmd=${BASH_SOURCE:-$0} # see http://mywiki.wooledge.org/BashFAQ/028 for a discussion of why $0 is not a good choice here
dir=$(dirname "$full_cmd")
cmd=${full_cmd##*/}

if [ -n "$WORKSPACE" ] && [ -e "$EDK_TOOLS_PATH/ImageTool" ]
then
  if [ $1 == 'IA32' ]
  then
    if [ ! -e "$EDK_TOOLS_PATH/ImageTool/ImageTool32" ]
    then
      echo "BaseTools C Tool binary was not found (ImageTool32)"
      echo "You may need to run:"
      echo "  make -C $EDK_TOOLS_PATH/ImageTool"
    else
      shift
      exec "$EDK_TOOLS_PATH/ImageTool/ImageTool32" "$@"
    fi
  elif [ $1 == 'X64' ]
  then
    if [ ! -e "$EDK_TOOLS_PATH/ImageTool/ImageTool64" ]
    then
      echo "BaseTools C Tool binary was not found (ImageTool64)"
      echo "You may need to run:"
      echo "  make -C $EDK_TOOLS_PATH/ImageTool"
    else
      shift
      exec "$EDK_TOOLS_PATH/ImageTool/ImageTool64" "$@"
    fi
  else
    echo "ImageTool for $1 is not supported"
    exit 127
  fi
else
  echo "Unable to find the real '$cmd' to run"
  echo "This message was printed by"
  echo "  $0"
  exit 127
fi
