## @file
#  Copyright (c) 2022, Mikhail Krichanov. All rights reserved.
#  SPDX-License-Identifier: BSD-3-Clause
##

PROJECT = MicroTool
PRODUCT = $(PROJECT)$(INFIX)$(SUFFIX)
OBJS    = $(PROJECT).o

DEBUG    = 1
SANITIZE = 0
OC_USER  = ../../OpenCorePkg
UDK_PATH = ../..

include $(OC_USER)/User/Makefile
